//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompras
    {
        public int id_compra { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string valor_compra { get; set; }
        public string valor_total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
