//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategorias
    {
        public tblCategorias()
        {
            this.tblProductos = new HashSet<tblProductos>();
            this.tblSubCategorias = new HashSet<tblSubCategorias>();
        }
    
        public int id_categoria { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual ICollection<tblProductos> tblProductos { get; set; }
        public virtual ICollection<tblSubCategorias> tblSubCategorias { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
