//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturas
    {
        public tblFacturas()
        {
            this.tblVentas = new HashSet<tblVentas>();
        }
    
        public int id_factura { get; set; }
        public string nombre { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> valor_bruto { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> valor_neto { get; set; }
        public string usuario { get; set; }
        public string numero_factura { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    
        public virtual tblSucursales tblSucursales { get; set; }
        public virtual ICollection<tblVentas> tblVentas { get; set; }
    }
}
