//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSucursales
    {
        public tblSucursales()
        {
            this.tblUsuarios = new HashSet<tblUsuarios>();
            this.tblFacturas = new HashSet<tblFacturas>();
            this.tblMovimientos = new HashSet<tblMovimientos>();
            this.tblProductos = new HashSet<tblProductos>();
        }
    
        public int id_sucursal { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual ICollection<tblUsuarios> tblUsuarios { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual ICollection<tblFacturas> tblFacturas { get; set; }
        public virtual ICollection<tblMovimientos> tblMovimientos { get; set; }
        public virtual ICollection<tblProductos> tblProductos { get; set; }
    }
}
