//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategorias
    {
        public tblSubCategorias()
        {
            this.tblProductos = new HashSet<tblProductos>();
        }
    
        public int id_subcategoria { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual tblCategorias tblCategorias { get; set; }
        public virtual ICollection<tblProductos> tblProductos { get; set; }
    }
}
