//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarios
    {
        public tblUsuarios()
        {
            this.tblPermisosUsuarios = new HashSet<tblPermisosUsuarios>();
        }
    
        public int id_usuario { get; set; }
        public string identificacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string password { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string username { get; set; }
        public string email { get; set; }
    
        public virtual tblRoles tblRoles { get; set; }
        public virtual tblSucursales tblSucursales { get; set; }
        public virtual ICollection<tblPermisosUsuarios> tblPermisosUsuarios { get; set; }
    }
}
