//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIngresosGastos
    {
        public string FacturaOCompra { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> credito { get; set; }
        public Nullable<decimal> debito { get; set; }
        public int id_factura { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    }
}
